#!/bin/sh

set -eu

for f in "${@}"
do
	sed -i "s|é|\\\\'e|g" "${f}"
	sed -i 's|è|\\`e|g' "${f}"
	sed -i 's|ê|\\^e|g' "${f}"

	sed -i 's|à|\\`a|g' "${f}"
	sed -i 's|â|\\^a|g' "${f}"

	sed -i 's|ç|\\c{c}|g' "${f}"
done
