#!/bin/sh

set -eu

for f in "${@}"
do
	sed -i "s|\'e|\\\\'e|g" "${f}"
	sed -i 's|\`e|\\`e|g' "${f}"
	sed -i 's|\^e|\\^e|g' "${f}"

	sed -i "s|\'E|\\\\'E|g" "${f}"
	sed -i 's|\`E|\\`E|g' "${f}"
	sed -i 's|\^E|\\^E|g' "${f}"

	sed -i 's|\`a|\\`a|g' "${f}"
	sed -i 's|\^a|\\^a|g' "${f}"

	sed -i 's|\`A|\\`A|g' "${f}"
	sed -i 's|\^A|\\^A|g' "${f}"
done
